files: (?x)^(terraform/.*)
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-no-color
          - --args=-diff
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
